-- Midnight Signal v11.46 notes
-- No schema change is required for webhook sync because entitlement status is stored
-- inside public.user_state.state JSON. The webhook route uses the Supabase service role
-- to find matching rows by stored Stripe identifiers and update state.entitlement.
--
-- Required env vars for webhook sync:
-- NEXT_PUBLIC_SUPABASE_URL
-- SUPABASE_SERVICE_ROLE_KEY
-- STRIPE_SECRET_KEY
-- STRIPE_WEBHOOK_SECRET
