export const DEFAULT_STATE = {
  mode: 'Beginner',
  currency: 'USD',
  strategy: 'Swing',
  timeframe: '1H',
  selectedAsset: 'BTC',
  profileId: null,
  dashboardFocus: 'Track signals',
  onboardingGoal: 'Track signals',
  profileName: 'My setup',
  watchlist: ['BTC', 'ETH', 'ADA', 'SOL'],
  savedProfiles: [null, null, null],
  alerts: [],
  acceptedDisclaimer: false,
  lastViewedAt: null,
  updatedAt: null,
  deviceLabel: 'This device',
  liveUpdatesEnabled: true,
  liveRefreshInterval: '60',
  livePulseEnabled: true,
  signalSoundsEnabled: false,
  alertDeliveryEnabled: false,
  alertDeliveryEmail: '',
  alertCooldownMinutes: '30',
  alertDigestMode: 'instant',
  alertDigestIntervalMinutes: '240',
  alertLastDeliveryAt: null,
  alertLastDeliveryStatus: '',
  recentAlertEvents: [],
  alertMemory: { assetMap: {}, triggerLog: {} },
  alertDigestMemory: { queued: [], lastSentAt: null },
  entitlement: {
    status: 'inactive',
    verified: false,
    source: 'local',
    customerId: null,
    subscriptionId: null,
    checkoutSessionId: null,
    priceId: null,
    currentPeriodEnd: null,
    checkedAt: null,
    lastEventAt: null,
    lastError: ''
  },
  stripeWebhookStatus: '',
  stripeWebhookUpdatedAt: null,
  planTier: 'basic'
};

export const MARKET_FIXTURES = [
  { symbol: 'BTC', name: 'Bitcoin', conviction: 78, sentiment: 'bullish', story: 'Holding trend structure while momentum remains constructive.' },
  { symbol: 'ETH', name: 'Ethereum', conviction: 63, sentiment: 'neutral', story: 'Strength improving, but still waiting on cleaner follow-through.' },
  { symbol: 'ADA', name: 'Cardano', conviction: 74, sentiment: 'bullish', story: 'Leadership tone improving with a stronger recovery posture.' },
  { symbol: 'SOL', name: 'Solana', conviction: 46, sentiment: 'neutral', story: 'Momentum is mixed after a quick stretch higher.' },
  { symbol: 'XRP', name: 'XRP', conviction: 39, sentiment: 'bearish', story: 'Still lagging relative strength leaders.' }
];
